apiVersion: v1
kind: Pod
metadata:
  name: samplepod-1
  namespace: router
  annotations:
    k8s.v1.cni.cncf.io/networks: ovs-net-1
spec:
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: alpine

