apiVersion: v1
kind: Pod
metadata:
  name: samplepod-2
  namespace: router
  annotations:
#    k8s.v1.cni.cncf.io/networks: ovs-net-1
    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
#    k8s.v1.cni.cncf.io/networks: '[
#        {
#          "name": "ovs-net-1",
#          "ips": ["10.10.10.1/24"]
#        }
#]'
spec:
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-3
  namespace: router
  annotations:
#    k8s.v1.cni.cncf.io/networks: ovs-net-1
    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
#    k8s.v1.cni.cncf.io/networks: '[
#        {
#          "name": "ovs-net-1",
#          "ips": ["10.10.10.2/24"]
#        }
#]'
spec:
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: alpine
